# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
docs/openapi.yaml:
  no-server-example.com:
    - '#/servers/0/url'
    - '#/servers/1/url'
  no-unused-components:
    - '#/components/schemas/Benchmark'
    - '#/components/schemas/EvaluationResult'
    - '#/components/schemas/ProviderType'
