name: Feature Request
description: Suggest a new feature or enhancement for eval-hub
title: "[Feature]: "
labels: ["kind/feature", "status/triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your use case and requirements.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve? Is your feature request related to a problem?
      placeholder: I'm always frustrated when... / There is no way to... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see... / The feature should work by...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a real-world scenario where this feature would be useful.
      placeholder: |
        As a [role], I want to [action] so that [benefit].

        Example scenario:
        1. I have a model that...
        2. I need to evaluate it using...
        3. The current system doesn't allow me to...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component Area
      description: Which area of eval-hub would this feature affect?
      options:
        - API Endpoints
        - Evaluation Executors
        - MLFlow Integration
        - Collection Management
        - Deployment (Local/Podman/Kubernetes/OpenShift)
        - Configuration Management
        - Monitoring/Metrics
        - Documentation
        - CLI/Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your workflow?
      options:
        - Critical - Blocking current work
        - High - Important for productivity
        - Medium - Would be nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I have considered... / Other approaches might be... / Alternative tools that do this...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Notes
      description: |
        If you have ideas about implementation, technical considerations, or constraints, please share them.
        This is optional but can help with feasibility assessment.
      placeholder: |
        Technical considerations:
        - API design implications
        - Database schema changes
        - Performance impact
        - Backward compatibility
        - Dependencies required

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: |
        What would need to be implemented for you to consider this feature complete?
        Please provide specific, testable criteria.
      placeholder: |
        - [ ] I can do X via the API
        - [ ] The feature handles Y scenario
        - [ ] Error handling works for Z case
        - [ ] Documentation is updated
        - [ ] Tests are included

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested already
          required: true
        - label: I have reviewed the documentation to confirm this functionality doesn't already exist
          required: true
        - label: I am willing to help test this feature when implemented
          required: false
        - label: I am interested in contributing to the implementation
          required: false
