apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eval-hub-service-full-access
  namespace: default
rules:
  - apiGroups:
      - trustyai.opendatahub.io
    resources:
      - evaluations
      - collections
      - providers
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eval-hub-service-full-access
  namespace: default
subjects:
  - kind: ServiceAccount
    name: test-sa
    namespace: default
roleRef:
  kind: Role
  name: eval-hub-service-full-access
